import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar/Navbar";
import Theme from "./theme-provider";
import "react-toastify/dist/ReactToastify.css";
import { Flip, ToastContainer } from "react-toastify";
import { ReduxProvider } from "./redux/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={inter.className}>
        <Theme>
          <ReduxProvider>
            <Navbar />
            <main className="min-h-[calc(100vh-var(--nav-h))] flex flex-col justify-center">
              {children}
              <ToastContainer theme="light" transition={Flip} />
            </main>
          </ReduxProvider>
        </Theme>
      </body>
    </html>
  );
}
